monolog:
    handlers:
        custom_handler:
            type: stream
            path: '%kernel.logs_dir%/custom.log'
            level: debug
            channels: ['custom_log']

        new_service_handler:
            level: debug
            type: stream
            path: '%kernel.logs_dir%/new_service.log'
            channels: [ 'new_log' ]

    channels: ['new_log', 'custom_log']

