twig:
    default_path: "%kernel.project_dir%/templates"
    paths:
        '%kernel.project_dir%/src/DemoBundle/src/templates': DemoBundle
        '%kernel.project_dir%/bundles/ProductBundle/src/templates': ProductBundle
        '%kernel.project_dir%/bundles/SpyBundle/src/templates': SpyBundle

