pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    Gallery:
                        items: {  }
                        medias: {  }
                        name: Gallery
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1695973757
                        creationDate: 1695973751
                        preserveAnimation: false
