pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    Room:
                        items:
                            -
                                method: frame
                                arguments:
                                    width: 400
                                    height: 400
                                    forceResize: true
                            -
                                method: setBackgroundColor
                                arguments:
                                    color: '#00c1c8c8'
                            -
                                method: roundCorners
                                arguments:
                                    width: 10
                                    height: 16
                            -
                                method: rotate
                                arguments:
                                    angle: 45
                        medias: {  }
                        name: Room
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1697008289
                        creationDate: 1695968845
                        preserveAnimation: false
