pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    Shirt:
                        items: {  }
                        medias: {  }
                        name: Shirt
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1697712225
                        creationDate: 1697712214
                        preserveAnimation: false
