_pimcore:
    resource: "@PimcoreCoreBundle/config/routing.yaml"

app:
    resource: "../src/Controller/"
    type: annotation

room_preview:
    path: '/room/{roomNumber}/{description}'
    controller: 'App\Controller\RoomController::show'
    requirements:
        roomNumber: '\d+' # Ensure roomNumber is a number