pimcore:
    assets:
        video:
            thumbnails:
                definitions:
                    content:
                        items: {  }
                        medias: {  }
                        name: content
                        description: ''
                        group: ''
                        videoBitrate: 600
                        audioBitrate: 128
                        modificationDate: 1697009238
                        creationDate: 1695927112
