services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    ConnectBundle\Controller\:
        resource: '../src/Controller'
        public: true
        tags: ['controller.service_arguments']

    ConnectBundle\Tool\Installer:
        public: true
    #        arguments:
    #            $bundle: "@=service('kernel').getBundle('ConnectBundle')"

    ConnectBundle\Service\SmsService:
        arguments:
            $httpClient: '@http_client'
            $smsApiUrl: 'https://eoe7erpc4lrbado.m.pipedream.net'
            $apiKey: 'Rishan@27'

    ConnectBundle\Messenger\Handler\SmsNotificationHandler:
        arguments:
            $smsService: '@ConnectBundle\Service\SmsService'
#        tags:
#            - { name: 'messenger.message_handler' }

#    SpyBundle\Message\MessageHandler\DPEHandler:
#        tags:
#            - { name: 'messenger.message_handler', bus: 'messenger.bus.async' }

#    connect.controller.data_object_api:
#        class: ConnectBundle\Controller\DataObjectApiController
#        parent: 'pimcore.controller.frontend'
#        public: true



# add more services, or override services that need manual wiring
#    DemoBundle\ExampleClass:
#        arguments:
#            - "@service_id"
#            - "plain_value"
#            - "%parameter%"
